# Ensures podman is installed
- name: "Install dependencies (dnf)"
  ansible.builtin.dnf:
    name:
    - podman
    state: present

- name: Create kea project directory
  file:
    path: "{{ kea_paths_home }}"
    state: directory

- name: Copy kea quadlet templates
  template:
    src: coredns.container.j2
    dest: "{{ coredns_paths_home }}/coredns.container"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
  - restart kea

- name: Symlink container file to /etc/containers/systemd
  file:
    path: /etc/containers/systemd/coredns.container
    state: link
    src: "{{ coredns_paths_home }}/coredns.container"

- name: Pull coredns image
  podman_image:
    name: "{{ coredns_container_image }}"
    pull: yes
    state: present
  notify:
  - restart coredns
