name: Build Kea Image
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 1 * *"
  push:
    branches:
      - master
    paths:
      - images/**
jobs:
  push:
    name: "kea_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
        - kea-2.6
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./images/
          file: ./images/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            docker.io/ccarney16/kea:${{ matrix.tag }}